os: linux
artifacts: bionic
language: c

matrix:
  include:
    # Linux - amd64
    - env: NIM_VERSION=0.20.2
    - env: NIM_VERSION=1.0.8
    - env: NIM_VERSION=1.2.6
    - env: NIM_VERSION=devel

    ## Uncomment to test on Linux - arm64
    # - arch: arm64
    #   env: NIM_VERSION=1.2.6

    ## Uncomment to test on Linux - ppc64
    # - arch: ppc64le
    #   env: NIM_VERSION=1.2.6

    # macOS - amd64
    - os: osx
      env: NIM_VERSION=0.20.2
    - os: osx
      env: NIM_VERSION=1.0.8
    - os: osx
      env: NIM_VERSION=1.2.6
    - os: osx
      env: NIM_VERSION=devel

    # windows - amd64
    - os: windows
      env: NIM_VERSION=0.20.2
    - os: windows
      env: NIM_VERSION=1.0.8
    - os: windows
      env: NIM_VERSION=1.2.6
    - os: windows
      env: NIM_VERSION=devel

cache:
  directories:
    - "$HOME/.choosenim"
    - "$HOME/.nimble"
    - "$HOME/.cache"

install:
  - |
    # Put env vars shared across all matrices here
    export NIM_CI_VERSION=github-workflows # or vX.Y.Z to lock to a specific nim-c version
  - |
    curl https://raw.githubusercontent.com/elijahr/nim-ci/${NIM_CI_VERSION}/nim-ci.sh -LsSf > nim-ci.sh
    source nim-ci.sh

script
  - all_the_things
