name: Build

on:
  push:
    branches: [ '*' ]
    tags: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build_amd64:
    name: Build ${{ matrix.builder }} x86_64
    runs-on: ${{ matrix.builder }}

    strategy:
      matrix:
        include:
          - builder: ubuntu-18.04
            nim_version: devel
          - builder: macos-latest
            nim_version: devel
          - builder: windows-latest
            nim_version: devel

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache
            ~/.choosenim
            ~/.nimble
          key: build_nim-${{ matrix.nim_version }}_${{ matrix.builder }}_x86_64

      - name: Install & build
        id: build
        env:
          # Put env vars shared across all matrices here
          GITHUB_TOKEN: ${{ github.token }}
          NIM_VERSION: ${{ matrix.nim_version }}
          NIM_CI_VERSION: github-workflows # or vX.Y.Z to lock to a specific nim-ci version
        shell: bash
        run: |
          curl https://raw.githubusercontent.com/elijahr/nim-ci/${NIM_CI_VERSION}/nim-ci.sh -LsSf > nim-ci.sh
          source nim-ci.sh

          ln -s "${ARTIFACTS_DIR}" ./artifacts

          all_the_things

      - name: Upload artifacts
        if: ${{ github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/') }}
        uses: actions/upload-artifact@v2
        with:
          path: ./artifacts/*

  # Build for Linux aarch64, ppc64le, etc
  build_linux_other_archs:
    name: Build ubuntu-18.04
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - nim_version: stable
            arch: aarch64
          - nim_version: stable
            arch: ppc64le

    steps:
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.ccache
            ~/.choosenim
            ~/.nimble
          key: build_nim-${{ matrix.nim_version }}_ubuntu-18.04_${{ matrix.arch }}

      - uses: actions/checkout@v2.1.0

      # Use run-on-arch-action to emulate the CPU architecture.
      # See https://github.com/uraimo/run-on-arch-action for docs.
      - name: Build
        id: build
        uses: elijahr/run-on-arch-action@container-name
        with:
          arch: ${{ matrix.arch }}
          distro: ubuntu18.04

          githubToken: ${{ github.token }}

          # Put env vars shared across all matrix nodes here
          env: | # YAML, but `|` is necessary
            GITHUB_TOKEN: ${{ github.token }}
            NIM_VERSION: ${{ matrix.nim_version }}
            NIM_CI_VERSION: github-workflows

          # Create cached/volume directories on host
          setup: |
            mkdir -p ~/.cache
            mkdir -p ~/.ccache
            mkdir -p ~/.choosenim
            mkdir -p ~/.nimble
            mkdir -p ~/artifacts

          # Mount cached directories in the container for faster builds
          dockerRunArgs: |
            --volume "${HOME}/.cache:/root/.cache"
            --volume "${HOME}/.ccache:/root/.ccache"
            --volume "${HOME}/.choosenim:/root/.choosenim"
            --volume "${HOME}/.nimble:/root/.nimble"
            --volume "${HOME}/artifacts:/artifacts"

          # Install some deps, gets cached as a docker image layer
          install: |
            apt-get update -q -y
            apt-get install git curl build-essential ccache -q -y
            /usr/sbin/update-ccache-symlinks
            echo 'export PATH="/usr/lib/ccache:$PATH"' | tee -a ~/.bashrc

          run: |
            curl https://raw.githubusercontent.com/elijahr/nim-ci/${NIM_CI_VERSION}/nim-ci.sh -LsSf > nim-ci.sh
            source nim-ci.sh

            ln -s "${ARTIFACTS_DIR}" ./artifacts

            all_the_things

      - name: Fix cache permissions
        run: |
          chmod -R 777 ~/.cache
          chown -R $(whoami) ~/.cache
          chmod -R 777 ~/.ccache
          chown -R $(whoami) ~/.ccache
          chmod -R 777 ~/.choosenim
          chown -R $(whoami) ~/.choosenim
          chmod -R 777 ~/.nimble
          chown -R $(whoami) ~/.nimble

      - name: Upload artifacts
        if: ${{ github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/') }}
        uses: actions/upload-artifact@v2
        with:
          path: ./artifacts/*
