version: '3'
services:
  distcc-host:
    image: elijahru/distcc-host:latest-debian-buster
    ports:
      - 3635:3635 # aarch64/arm64v8 cross-compiler
      - 3636:3636 # ppc64le cross-compiler

  distcc-client-arm64v8:
    build:
      context: .
      dockerfile: Dockerfile.arm64v8
    volumes:
      - .:/code
      - ./caches/arm64v8/ccache:/root/.ccache
    # command: [ 'bash', './code/tests/run.sh' ]

  distcc-client-ppc64le:
    build:
      context: .
      dockerfile: Dockerfile.ppc64le
    volumes:
      - .:/code
      - ./caches/ppc64le/ccache:/root/.ccache
