os: linux
dist: bionic
language: c

matrix:
  include:
    # Linux - amd64
    - env: BRANCH=0.20.2
    - env: BRANCH=1.0.8
    - env: BRANCH=1.2.6
    - env: BRANCH=devel

    ## Uncomment to test on Linux - arm64
    # - arch: arm64
    #   env: BRANCH=1.2.6

    ## Uncomment to test on Linux - ppc64
    # - arch: ppc64le
    #   env: BRANCH=1.2.6

    # macOS - amd64
    - os: osx
      env: BRANCH=0.20.2
    - os: osx
      env: BRANCH=1.0.8
    - os: osx
      env: BRANCH=1.2.6
    - os: osx
      env: BRANCH=devel

    # windows - amd64
    - os: windows
      env: BRANCH=0.20.2
    - os: windows
      env: BRANCH=1.0.8
    - os: windows
      env: BRANCH=1.2.6
    - os: windows
      env: BRANCH=devel

cache:
  directories:
    - "$HOME/.choosenim" # cache nim binaries

install:
  # Set up environment with CI convenience functions and install nim
  - source `curl https://raw.githubusercontent.com/elijahr/nim-ci/master/nim-ci.sh -LsSf`
  - install_nim

script:
  # nimble build or nimble install your project.
  # autodetects which depending on if your project's nimble config exports a bin or not.
  - install_or_build_nim_project

  # Run unit tests
  - cd_to_nim_project
  - nimble test
