name: Build

on:
  push:
    branches: [ '*' ]
    tags: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    name: Build ${{ matrix.os }} amd64
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ ubuntu-latest ]
        nim_version: [ devel ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Install nim
        shell: bash
        env:
          NIM_VERSION: ${{ matrix.nim_version }}
          CPU_ARCH: amd64
          OS_NAME: ${{ matrix.os }}

        run: |
          curl https://raw.githubusercontent.com/elijahr/nim-ci/github-workflows/install_nim.sh?asd -LsSf -o install_nim.sh
          cat install_nim.sh
          source install_nim.sh

      - name: Install dependencies
        run: |
          nimble install -y -d

      - name: Run tests
        run: |
          nimble test

      # - name: Upload binaries for ${{ matrix.arch }}
      #   uses: actions/upload-artifact@v2
      #   with:
      #     path: |
      #       bin/*
      #   if: ${{ github.event_name == "tags" }}

  build-linux-arm64:
    name: Build Linux arm64
    runs-on: ubuntu-latest

    strategy:
      matrix:
        nim_version: [ devel ]

    steps:
      - name: Build arm64
        id: build_arm64
        uses: uraimo/run-on-arch-action@v1.1.0
        with:
          architecture: aarch64
          # TODO - use alpine, its smaller?
          distribution: ubuntu18.04
          run: |
            export NIM_VERSION=${{ matrix.nim_version }}
            export CPU_ARCH=arm64
            export OS_NAME=linux

            export DEBIAN_FRONTEND=noninteractive
            apt-get update -q
            apt-get install -q -y build-essential

            curl https://raw.githubusercontent.com/elijahr/nim-ci/github-workflows/install_nim.sh?asd -LsSf -o install_nim.sh
            cat install_nim.sh
            source install_nim.sh

            mkdir foo
            echo "baz" >> foo/bar.txt
            tar czf foo.tar.gz foo
            echo ::set-output name=foo::$(cat foo.tar.gz)

      - name: Cat binaries
        run: |
          cat << EOF > foo.tar.gz
          ${{ steps.build_arm64.outputs.foo }}
          EOF
          tar xzf foo.tar.gz
          cat foo/bar.txt

      # - name: Upload binaries for arm64
      #   uses: actions/upload-artifact@v2
      #   with:
      #     path: |
      #       bin/*
      #   if: ${{ github.event_name == "tags" }}
