name: Build

on:
  push:
    branches: [ '*' ]
    tags: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build_amd64:
    name: Build ${{ matrix.nim_host_os }}_amd64
    runs-on: ${{ matrix.builder }}

    strategy:
      matrix:
        include:
          - builder: ubuntu-18.04
            nim_version: devel
          - builder: macos-latest
            nim_version: devel
          - builder: windows-latest
            nim_version: devel

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.choosenim_${{ matrix.nim_version }}_${{ matrix.builder }}_x86_64
            ~/.nimble_${{ matrix.nim_version }}_${{ matrix.builder }}_x86_64

      - name: Install & build
        id: build
        env:
          # Put env vars shared across all matrices here
          NIM_VERSION: ${{ matrix.nim_version }}
          NIM_CI_VERSION: github-workflows # or vX.Y.Z to lock to a specific nim-ci version
        shell: bash
        run: |
          ln -s ~/.choosenim_${{ matrix.nim_version }}_${{ matrix.builder }}_x86_64 ~/.choosenim
          ln -s ~/.nimble_${{ matrix.nim_version }}_${{ matrix.builder }}_x86_64 ~/.nimble

          curl https://raw.githubusercontent.com/elijahr/nim-ci/${NIM_CI_VERSION}/nim-ci.sh -LsSf > nim-ci.sh
          source nim-ci.sh

          all_the_things

      - name: Upload artifacts
        if: ${{ github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/') }}
        uses: actions/upload-artifact@v2
        with:
          path: ./artifacts/*

  # Build for Linux aarch64, ppc64le, etc
  build_linux_other_archs:
    name: Build linux_${{ matrix.nim_host_cpu }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - nim_version: stable # The version of Nim to test with
            arch: aarch64 # For run-on-arch-action

    steps:
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.choosenim-ubuntu-18.04-${{ matrix.arch }}
            ~/.nimble-ubuntu-18.04-${{ matrix.arch }}
          key: ${{ matrix.nim_version }}_linux_${{ matrix.arch }}

      - uses: actions/checkout@v2.1.0

      # Use run-on-arch-action to emulate the CPU architecture.
      # See https://github.com/uraimo/run-on-arch-action for docs.
      - name: Build
        id: build
        uses: elijahr/run-on-arch-action@fix-args
        with:
          arch: ${{ matrix.arch }}
          distro: ubuntu18.04

          githubToken: ${{ github.token }}

          # Put env vars shared across all matrix nodes here
          env: | # YAML, but `|` is necessary
            NIM_VERSION: ${{ matrix.nim_version }}
            NIM_CI_VERSION: github-workflows

          # Create cached directories
          setup: |
            mkdir -p ~/.choosenim-ubuntu-18.04-${{ matrix.arch }}
            mkdir -p ~/.nimble-ubuntu-18.04-${{ matrix.arch }}
            mkdir -p ./artifacts

          # Mount cached directories in the container for faster builds
          dockerRunArgs: |
            --volume ~/.choosenim-ubuntu-18.04-${{ matrix.arch }}:/root/.choosenim
            --volume ~/.nimble-ubuntu-18.04-${{ matrix.arch }}:/root/.nimble
            --volume ./artifacts:/artifacts

          run: |
            apt-get update -q
            apt-get install -q -y build-essential git curl bash

            curl https://raw.githubusercontent.com/elijahr/nim-ci/${NIM_CI_VERSION}/nim-ci.sh -LsSf > nim-ci.sh
            source nim-ci.sh

            all_the_things

      - name: Upload artifacts
        if: ${{ github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/') }}
        uses: actions/upload-artifact@v2
        with:
          path: ./artifacts/*
