name: Test

on:
  push:
    branches: [ '*' ]
    tags: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  # test_amd64:
  #   name: Test ${{ matrix.builder }} x86_64
  #   runs-on: ${{ matrix.builder }}

  #   strategy:
  #     matrix:
  #       include:
  #         - builder: ubuntu-18.04
  #         - builder: macos-latest
  #         - builder: windows-latest

  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 1
  #         submodules: recursive

  #     - name: Setup cache
  #       uses: actions/cache@v2
  #       with:
  #         path: |
  #           ~/.cache
  #         key: test_${{ matrix.builder }}_x86_64

  #     - name: Run tests
  #       id: test
  #       env:
  #         GITHUB_TOKEN: ${{ github.token }}
  #         NIM_CI_TEST_FULL_CLEAN: yes
  #       run: |
  #         bash ./tests/run.sh

  # Build for Linux aarch64, ppc64le, etc
  test_linux_other_archs:
    name: Test ${{ matrix.arch }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [ arm64v8, ppc64le ]

    steps:
      - uses: actions/checkout@v2.1.0

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: |
            caches
          key: test_${{ matrix.arch }}

      - name: Install dependencies
        run: |
          sudo apt-get update -q -y
          sudo apt-get -qq install -y qemu qemu-user-static curl
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Start distccd
        run: docker-compose up -d distcc-host

      - name: Run tests
        run: docker-compose up distcc-client-${{ matrix.arch }}

      - name: Fix cache permissions
        run: chmod -R 777 caches && chown -R $(whoami) caches
